version: '3'
services: 
    web:
        image: nginx
        container_name: nginx
        ports: 
            - 8000:80
        volumes: 
            - "./src/backend/:/var/www/html"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx:/etc/nginx/conf.d"
        restart: always
        depends_on: 
            - php
            - mysql
    php:
        build: 
            context: .
            dockerfile: ./docker/Fpm.Dockerfile  
        container_name: php
        volumes: 
            - "./src/backend/:/var/www/html"  
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini" 
        restart: always
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0.23
        restart: always
        ports:
            - "8989:3306"
        container_name: mysql
        environment:
            - MYSQL_DATABASE=u_path
            - MYSQL_ROOT_PASSWORD=root
        
